### ISSUE TITLE
Still using java 8u161 ?

### ISSUE THREAD

**Issue by schweikert** [jboss-dockerfiles/base-jdk#11]
Latest image was built 4 months ago. It seems that some important security patches were implemented since then.

See:
- https://www.oracle.com/technetwork/java/javase/8u162-relnotes-4021436.html
- http://www.oracle.com/technetwork/java/javase/8u172-relnotes-4308893.html
- http://www.oracle.com/technetwork/java/javase/8u181-relnotes-4479407.html

**Comment by goldmann** [comment]
I'm not sure why it was not rebuild when a new CentOS image was pushed, the linking just stopped to work. I kicked builds manually. Thanks for letting me know!
