### ISSUE TITLE
Critical issue in OpenJDK 1.8.0.181 -- rebuild for 1.8.0.191?

### ISSUE THREAD

**Issue by jonasholtkamp** [jboss-dockerfiles/base-jdk#12]
The following critical issue has been raised for OpenJDK: https://access.redhat.com/errata/RHSA-2018:2942. [As per the latest build logs](https://hub.docker.com/r/jboss/base-jdk/builds/bq3qxmnfaapktv2xoozkfnj/) for `base-jdk:8` an affected version is installed (1.8.0.181)

Apparently the issue is fixed with version 1.8.0.191. Could you provide a rebuilt `base-jdk:8` image with this fix applied?

**Comment by goldmann** [comment]
Done!
