### ISSUE TITLE
Updat to java8 u72

### ISSUE THREAD

**Issue by edwinrolle** [jboss-dockerfiles/base-jdk#2]
Please update to java8 u72 in order to get fixes for the following issues:
http://www.oracle.com/technetwork/topics/security/cpujan2016-2367955.html

**Comment by 2d6** [comment]
Is this image even maintained by anyone? I mean, the last commit was a year ago: "Switched to version 8 of OpenJDK". Really? No wonder it still uses 1.8.0_51.

**Comment by goldmann** [comment]
First of all - there is **no** direct relation between a commit and a built image.

When a rebuild is done (for example triggered manually), a new version (latest available in the repositories) of JDK is picked up. Last build was [done 13 hours ago](https://hub.docker.com/r/jboss/base-jdk/builds/bztulgogibqagdhwfx6cpv6/) which pulls `1.8.0.71-2.b15.el7_2`. I'm not sure why this is not visible under the tag `8`, though. For me it looks like a Docker HUB issue. I'll investigate.

**Comment by goldmann** [comment]
I've just tested this with a fresh Docker and it works. It seems this was an issue with my local copy of the image - it somehow used old image for the new tag.

```
$ docker -H unix:///tmp/docker-v1.sock pull jboss/base-jdk:8
8: Pulling from jboss/base-jdk

fa5be2806d4c: Pull complete 
2bf4902415e3: Pull complete 
86bcb57631bd: Pull complete 
c8a648134623: Pull complete 
e4999ea89283: Pull complete 
1b92a1e794d1: Pull complete 
1635aaefce35: Pull complete 
fe2b1e135053: Pull complete 
94415a6cdaf4: Pull complete 
c1dcf48f4fb5: Pull complete 
d12db9913d45: Pull complete 
f65d578ca204: Pull complete 
75833c40f336: Pull complete 
28e6d293c05c: Pull complete 
Digest: sha256:fbddde558b33e28efd664845301705028c0230bf2c144aed3a4964ff3a21d4be
Status: Downloaded newer image for jboss/base-jdk:8
$ docker -H unix:///tmp/docker-v1.sock run -it --rm jboss/base-jdk:8 rpm -qa | grep java 
python-javapackages-3.4.1-11.el7.noarch
tzdata-java-2015g-1.el7.noarch
java-1.8.0-openjdk-headless-1.8.0.71-2.b15.el7_2.x86_64
java-1.8.0-openjdk-1.8.0.71-2.b15.el7_2.x86_64
javapackages-tools-3.4.1-11.el7.noarch
java-1.8.0-openjdk-devel-1.8.0.71-2.b15.el7_2.x86_64
```

Closing this issue as the image contains latest available JDK.
