### ISSUE TITLE
Request to create two branches to support aarch64

### ISSUE THREAD

**Issue by KurtStam** [jboss-dockerfiles/base-jdk#5]
I'd like 2 branches:

aarch64-jdk7 for https://github.com/KurtStam/base-jdk/tree/aarch64-jdk7
aarch64-jdk8 for https://github.com/KurtStam/base-jdk/tree/aarch64-jdk8

to support the aarch64 architecture.

I will submit PR's as soon as the branches are created.
Thx!

--Kurt

**Comment by goldmann** [comment]
Done!
